In [1]:
import sys
import numpy
import sklearn
import pandas

print('Python: {}'.format(sys.version))
print('Numpy: {}'.format(numpy.__version__))
print('Sklearn: {}'.format(sklearn.__version__))
print('Pandas: {}'.format(pandas.__version__))

Python: 3.7.0 (default, Jun 28 2018, 07:39:16)
[Clang 4.0.1 (tags/RELEASE_401/final)]
Numpy: 1.15.1
Sklearn: 0.19.2
Pandas: 0.23.4

In [2]:
import numpy as np
import pandas as pd
names = ['Class', 'id', 'Sequence']
data = pd.read_csv("ML_200bp.txt", names = names)
print(data.iloc[0])

Class                                                       +
id                                                MSTRG.14696
Sequence    \t\tGAAGCTTTGCAGGAGCTTTCATGACTCATGTATTGAGGTCCT...
Name: 0, dtype: object

In [3]:
classes = data.loc[:, 'Class']
print(classes[:5])

0    +
1    -
2    -
3    +
4    +
Name: Class, dtype: object

In [4]:
# generate list of DNA sequences
sequences = list(data.loc[:, 'Sequence'])
dataset = {}

# loop through sequences and split into individual nucleotides
for i, seq in enumerate(sequences):
    
    # split into nucleotides, remove tab characters
    nucleotides = list(seq)
    nucleotides = [x for x in nucleotides if x != '\t']
    
    # append class assignment
    nucleotides.append(classes[i])
    
    # add to dataset
    dataset[i] = nucleotides
    
print(dataset[0])

['G', 'A', 'A', 'G', 'C', 'T', 'T', 'T', 'G', 'C', 'A', 'G', 'G', 'A', 'G', 'C', 'T', 'T', 'T', 'C', 'A', 'T', 'G', 'A', 'C', 'T', 'C', 'A', 'T', 'G', 'T', 'A', 'T', 'T', 'G', 'A', 'G', 'G', 'T', 'C', 'C', 'T', 'G', 'G', 'T', 'C', 'G', 'A', 'A', 'G', 'G', 'A', 'G', 'A', 'A', 'T', 'C', 'A', 'A', 'G', 'A', 'T', 'A', 'G', 'A', 'G', 'A', 'T', 'T', 'A', 'A', 'G', 'T', 'T', 'T', 'G', 'T', 'C', 'T', 'G', 'A', 'A', 'A', 'G', 'A', 'G', 'G', 'A', 'A', 'G', 'A', 'A', 'G', 'G', 'A', 'G', 'A', 'A', 'G', 'T', 'G', 'T', 'G', 'T', 'T', 'G', 'T', 'C', 'A', 'T', 'C', 'T', 'T', 'G', 'A', 'A', 'C', 'T', 'A', 'G', 'G', 'C', 'T', 'A', 'A', 'G', 'C', 'T', 'G', 'A', 'G', 'G', 'A', 'T', 'G', 'G', 'T', 'A', 'T', 'T', 'T', 'G', 'T', 'G', 'A', 'A', 'A', 'C', 'A', 'T', 'A', 'T', 'T', 'A', 'T', 'C', 'A', 'T', 'T', 'T', 'T', 'C', 'T', 'T', 'T', 'T', 'G', 'T', 'T', 'A', 'T', 'G', 'C', 'T', 'T', 'C', 'T', 'T', 'T', 'A', 'C', 'G', 'C', 'A', 'T', 'G', 'A', 'T', 'A', 'T', 'G', 'T', 'A', 'G', 'G', 'C', 'T', 'T', 'A', 'G', '+']

In [5]:
dframe = pd.DataFrame(dataset)
print(dframe)

    0    1    2    3    4    5    6    7    8    9    ...  4990 4991 4992  \
0      G    T    C    T    T    T    G    G    A    A ...     A    A    T
1      A    T    C    C    C    G    C    T    A    A ...     T    T    A
2      A    T    G    G    C    T    A    T    T    G ...     T    G    A
3      G    T    G    G    G    A    G    T    G    G ...     C    G    G
4      C    A    C    G    A    C    C    G    T    T ...     C    A    G
5      T    C    A    T    C    T    T    T    A    A ...     T    T    G
6      T    C    T    T    A    T    T    T    T    G ...     A    C    A
7      T    T    A    C    A    G    A    T    T    T ...     T    A    G
8      G    T    A    G    C    T    T    T    T    A ...     T    T    C
9      C    T    C    A    A    G    T    T    T    G ...     T    T    T
10     A    T    C    G    A    T    C    T    G    G ...     C    A    A
11     G    C    G    G    A    C    A    G    A    A ...     T    A    A
12     G    T    C    A    G    T    T    G    G    A ...     A    G    G
13     A    T    A    A    A    G    T    A    A    G ...     G    C    T
14     G    A    G    T    C    A    A    A    A    A ...     A    C    T
15     C    T    C    G    A    T    T    A    C    A ...     G    G    G
16     T    C    A    G    T    T    A    T    A    G ...     T    A    G
17     T    A    T    T    T    A    C    T    G    A ...     C    A    C
18     T    A    T    C    T    G    T    G    G    A ...     A    A    T
19     C    T    C    G    G    C    T    G    T    A ...     T    G    G
20     A    G    T    A    A    T    T    A    T    A ...     T    C    T
21     T    A    G    C    T    T    G    T    G    G ...     T    T    T
22     G    A    G    C    G    T    T    T    A    T ...     G    T    T
23     A    T    A    A    A    G    G    T    A    T ...     T    T    T
24     C    C    T    G    T    T    T    G    A    A ...     A    A    T
25     T    G    T    G    G    C    C    T    A    T ...     C    T    G
26     C    A    T    G    A    A    T    C    G    G ...     C    C    A
27     A    C    T    G    T    T    G    T    C    G ...     T    G    G
28     T    C    G    T    G    T    A    A    C    T ...     T    A    A
29     G    C    T    T    T    T    A    C    T    G ...     T    C    A
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ... ...   ...  ...  ...
171    G    A    A    C    T    C    C    A    G    C ...     T    G    A
172    C    T    T    T    C    C    C    C    T    T ...     G    A    A
173    T    A    T    C    T    T    A    A    T    T ...     A    A    A
174    T    A    A    T    A    T    A    C    A    G ...     A    T    G
175    C    G    A    T    G    G    T    A    C    A ...     C    G    T
176    T    A    C    A    A    T    G    A    A    A ...     T    G    A
177    T    C    T    A    C    C    C    G    G    A ...     C    A    C
178    T    C    T    A    G    A    T    G    A    T ...     A    C    C
179    A    T    A    A    G    T    T    T    A    A ...     T    C    C
180    C    C    T    T    T    T    C    G    G    T ...     T    A    A
181    G    A    T    A    G    C    C    T    C    A ...     T    A    G
182    C    C    C    C    T    T    T    T    A    A ...     G    T    G
183    A    A    T    A    T    A    A    T    G    T ...     T    A    A
184    T    A    C    T    A    T    G    G    C    G ...     A    A    A
185    G    A    A    C    C    T    T    A    A    T ...     C    G    G
186    A    C    T    A    T    G    G    T    G    C ...     T    C    G
187    T    A    G    A    A    G    A    G    G    T ...     T    C    A
188    A    C    A    T    G    T    T    A    G    T ...     G    A    A
189    T    T    A    A    T    T    G    A    C    G ...     T    A    G
190    G    C    G    A    A    G    A    T    A    T ...     T    G    C
191    T    A    T    A    A    T    T    T    A    A ...     T    A    A
192    A    C    C    G    G    C    C    G    T    C ...     T    G    G
193    G    A    A    A    A    T    C    A    T    T ...     G    C    T
194    G    A    G    G    G    A    G    C    T    A ...     A    T    T
195    C    G    G    T    T    G    G    G    A    T ...     T    T    C
196    T    T    A    T    T    T    T    G    T    A ...     T    G    T
197    T    G    T    T    G    T    C    T    T    T ...     T    A    C
198    A    A    T    A    A    G    A    G    C    T ...     G    T    C
199    G    T    A    G    T    T    T    A    T    G ...     T    T    T
200    +    -    -    +    +    +    +    -    +    - ...     +    +    +

    4993 4994 4995 4996 4997 4998 4999
0      T    C    C    T    G    C    A
1      A    A    C    A    C    T    C
2      G    A    C    G    T    G    T
3      A    G    A    T    A    A    C
4      T    A    T    T    T    C    G
5      G    G    C    A    A    A    A
6      G    G    A    T    A    A    C
7      G    C    C    T    G    G    C
8      A    C    C    C    G    T    A
9      T    G    T    T    A    C    C
10     C    T    G    C    T    G    A
11     T    G    A    C    G    T    C
12     T    T    C    A    G    T    T
13     A    G    C    A    G    C    G
14     T    T    A    A    T    C    T
15     C    G    T    C    A    G    C
16     T    G    C    C    C    C    A
17     C    A    A    T    G    T    T
18     T    T    C    T    T    G    G
19     G    G    T    A    C    G    A
20     T    A    C    G    A    A    T
21     A    C    G    G    A    T    T
22     T    G    A    A    A    T    T
23     G    G    T    A    G    C    G
24     C    T    C    G    A    G    A
25     A    T    A    A    C    T    T
26     T    C    C    T    G    C    A
27     A    C    A    T    G    A    C
28     A    A    T    A    C    G    C
29     C    A    C    A    T    C    A
..   ...  ...  ...  ...  ...  ...  ...
171    A    A    C    T    T    C    A
172    T    A    A    T    C    G    G
173    T    T    C    G    A    T    A
174    C    G    T    T    A    C    G
175    A    A    C    G    T    A    C
176    C    A    A    A    G    C    A
177    G    G    A    A    T    T    A
178    T    A    C    T    C    A    T
179    T    G    C    G    A    A    T
180    C    G    A    G    T    G    A
181    C    A    G    C    T    C    A
182    A    T    A    A    T    T    C
183    G    G    C    A    C    C    C
184    A    G    A    A    A    A    C
185    A    A    C    A    A    T    A
186    C    G    T    C    A    G    A
187    T    G    C    A    A    A    A
188    A    A    G    G    G    G    C
189    A    T    A    A    A    T    C
190    T    G    G    A    G    G    C
191    G    G    C    T    T    C    A
192    A    A    A    C    G    C    A
193    A    T    C    A    T    G    A
194    T    T    A    G    A    C    C
195    G    T    A    T    A    T    C
196    T    A    G    A    T    C    T
197    T    A    G    T    G    A    A
198    A    C    A    A    T    G    G
199    A    G    A    T    T    G    A
200    +    +    +    -    +    -    +

[201 rows x 5000 columns]

In [6]:
df = dframe.transpose()
print(df.iloc[:5])

  0   1   2   3   4   5   6   7   8   9   ... 191 192 193 194 195 196 197 198  \
0   G   A   A   G   C   T   T   T   G   C ...   T   A   G   G   C   T   T   A
1   T   T   T   T   A   C   C   T   T   T ...   A   C   A   A   G   T   G   A
2   C   C   G   G   C   A   T   A   A   C ...   T   C   A   G   G   A   T   T
3   T   C   G   G   G   T   T   C   G   A ...   A   G   A   G   T   T   T   A
4   T   C   C   G   A   C   A   A   C   A ...   A   G   A   G   T   T   G   A

  199 200
0   G   +
1   T   -
2   A   -
3   G   +
4   T   +

[5 rows x 201 columns]

In [7]:
df.rename(columns = {200: 'Class'}, inplace = True) 
print(df.iloc[:5])

   0  1  2  3  4  5  6  7  8  9  ...  191 192 193 194 195 196 197 198 199  \
0  G  A  A  G  C  T  T  T  G  C  ...    T   A   G   G   C   T   T   A   G
1  T  T  T  T  A  C  C  T  T  T  ...    A   C   A   A   G   T   G   A   T
2  C  C  G  G  C  A  T  A  A  C  ...    T   C   A   G   G   A   T   T   A
3  T  C  G  G  G  T  T  C  G  A  ...    A   G   A   G   T   T   T   A   G
4  T  C  C  G  A  C  A  A  C  A  ...    A   G   A   G   T   T   G   A   T

  Class
0     +
1     -
2     -
3     +
4     +

[5 rows x 201 columns]

In [8]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,191,192,193,194,195,196,197,198,199,Class
count,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000,...,5000,5000,5000,5000,5000,5000,5000,5000,5000,5000
unique,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,2
top,T,T,T,T,T,T,T,T,T,T,...,T,T,T,T,T,T,T,T,T,+
freq,1478,1476,1449,1520,1443,1443,1537,1462,1458,1490,...,1527,1541,1464,1557,1547,1557,1519,1527,1511,3779

In [9]:
series = []
for name in df.columns:
    series.append(df[name].value_counts())
    
info = pd.DataFrame(series)
details = info.transpose()
print(details)

        0       1       2       3       4       5       6       7       8  \
T  1478.0  1476.0  1449.0  1520.0  1443.0  1443.0  1537.0  1462.0  1458.0
A  1332.0  1356.0  1383.0  1368.0  1367.0  1359.0  1291.0  1338.0  1350.0
G  1141.0  1091.0  1112.0  1083.0  1094.0  1108.0  1079.0  1115.0  1130.0
C  1049.0  1077.0  1056.0  1029.0  1096.0  1090.0  1093.0  1085.0  1062.0
+     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN
-     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN

        9   ...       191     192     193     194     195     196     197  \
T  1490.0   ...    1527.0  1541.0  1464.0  1557.0  1547.0  1557.0  1519.0
A  1427.0   ...    1364.0  1342.0  1426.0  1400.0  1414.0  1327.0  1411.0
G  1116.0   ...    1100.0  1080.0  1072.0  1100.0  1075.0  1124.0  1121.0
C   967.0   ...    1009.0  1037.0  1038.0   943.0   964.0   992.0   949.0
+     NaN   ...       NaN     NaN     NaN     NaN     NaN     NaN     NaN
-     NaN   ...       NaN     NaN     NaN     NaN     NaN     NaN     NaN

      198     199   Class
T  1527.0  1511.0     NaN
A  1417.0  1344.0     NaN
G  1063.0  1153.0     NaN
C   993.0   992.0     NaN
+     NaN     NaN  3779.0
-     NaN     NaN  1221.0

[6 rows x 201 columns]

In [10]:
numerical_df = pd.get_dummies(df)
numerical_df.iloc[:5]

,0_A,0_C,0_G,0_T,1_A,1_C,1_G,1_T,2_A,2_C,...,198_A,198_C,198_G,198_T,199_A,199_C,199_G,199_T,Class_+,Class_-
0,0,0,1,0,1,0,0,0,1,0,...,1,0,0,0,0,0,1,0,1,0
1,0,0,0,1,0,0,0,1,0,0,...,1,0,0,0,0,0,0,1,0,1
2,0,1,0,0,0,1,0,0,0,0,...,0,0,0,1,1,0,0,0,0,1
3,0,0,0,1,0,1,0,0,0,0,...,1,0,0,0,0,0,1,0,1,0
4,0,0,0,1,0,1,0,0,0,1,...,1,0,0,0,0,0,0,1,1,0

In [11]:
df = numerical_df.drop(columns=['Class_-'])
df.rename(columns = {'Class_+': 'Class'}, inplace = True)
print(df.iloc[:5])

   0_A  0_C  0_G  0_T  1_A  1_C  1_G  1_T  2_A  2_C  ...    197_T  198_A  \
0    0    0    1    0    1    0    0    0    1    0  ...        1      1
1    0    0    0    1    0    0    0    1    0    0  ...        0      1
2    0    1    0    0    0    1    0    0    0    0  ...        1      0
3    0    0    0    1    0    1    0    0    0    0  ...        1      1
4    0    0    0    1    0    1    0    0    0    1  ...        0      1

   198_C  198_G  198_T  199_A  199_C  199_G  199_T  Class
0      0      0      0      0      0      1      0      1
1      0      0      0      0      0      0      1      0
2      0      0      1      1      0      0      0      0
3      0      0      0      0      0      1      0      1
4      0      0      0      0      0      0      1      1

[5 rows x 801 columns]

In [12]:
from sklearn import model_selection

# Create X and Y datasets for training
X = np.array(df.drop(['Class'], 1))
y = np.array(df['Class'])

# define seed for reproducibility
seed = 1

# split data into training and testing datasets
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=0.25, random_state=seed)

In [13]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score

# define scoring method
scoring = 'accuracy'

# Define models to train
names = ["Nearest Neighbors", "Gaussian Process",
         "Decision Tree", "Random Forest", "Neural Net", "AdaBoost",
         "Naive Bayes", "SVM Linear", "SVM RBF", "SVM Sigmoid"]

classifiers = [
    KNeighborsClassifier(n_neighbors = 3),
    GaussianProcessClassifier(1.0 * RBF(1.0)),
    DecisionTreeClassifier(max_depth=5),
    RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
    MLPClassifier(alpha=1),
    AdaBoostClassifier(),
    GaussianNB(),
    SVC(kernel = 'linear'), 
    SVC(kernel = 'rbf'),
    SVC(kernel = 'sigmoid')
]

models = zip(names, classifiers)

# evaluate each model in turn
results = []
names = []

for name, model in models:
    kfold = model_selection.KFold(n_splits=5, random_state = seed)
    cv_results = model_selection.cross_val_score(model, X_train, y_train, cv=kfold, scoring=scoring)
    results.append(cv_results)
    names.append(name)
    msg = "%s: %f (%f)" % (name, cv_results.mean(), cv_results.std())
    print(msg)
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    print('Test-- ',name,': ',accuracy_score(y_test, predictions))
    print()

    print(classification_report(y_test, predictions))

/Users/tin/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

Nearest Neighbors: 0.690133 (0.018811)
Test--  Nearest Neighbors :  0.7152

             precision    recall  f1-score   support

          0       0.32      0.22      0.26       288
          1       0.79      0.86      0.82       962

avg / total       0.68      0.72      0.69      1250

Gaussian Process: 0.750667 (0.013387)
Test--  Gaussian Process :  0.7632

             precision    recall  f1-score   support

          0       0.30      0.02      0.04       288
          1       0.77      0.99      0.86       962

avg / total       0.66      0.76      0.67      1250

Decision Tree: 0.704000 (0.022784)
Test--  Decision Tree :  0.756

             precision    recall  f1-score   support

          0       0.29      0.04      0.07       288
          1       0.77      0.97      0.86       962

avg / total       0.66      0.76      0.68      1250

Random Forest: 0.751200 (0.012439)
Test--  Random Forest :  0.7696

             precision    recall  f1-score   support

          0       0.00      0.00      0.00       288
          1       0.77      1.00      0.87       962

avg / total       0.59      0.77      0.67      1250

/Users/tin/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

Neural Net: 0.709333 (0.011896)
Test--  Neural Net :  0.7424

             precision    recall  f1-score   support

          0       0.37      0.17      0.24       288
          1       0.79      0.91      0.85       962

avg / total       0.69      0.74      0.70      1250

AdaBoost: 0.720533 (0.013162)
Test--  AdaBoost :  0.752

             precision    recall  f1-score   support

          0       0.39      0.14      0.20       288
          1       0.78      0.94      0.85       962

avg / total       0.69      0.75      0.70      1250

Naive Bayes: 0.666667 (0.009160)
Test--  Naive Bayes :  0.672

             precision    recall  f1-score   support

          0       0.36      0.55      0.44       288
          1       0.84      0.71      0.77       962

avg / total       0.73      0.67      0.69      1250

SVM Linear: 0.692800 (0.012610)
Test--  SVM Linear :  0.7112

             precision    recall  f1-score   support

          0       0.32      0.22      0.26       288
          1       0.79      0.86      0.82       962

avg / total       0.68      0.71      0.69      1250

SVM RBF: 0.751200 (0.012439)
Test--  SVM RBF :  0.7696

             precision    recall  f1-score   support

          0       0.00      0.00      0.00       288
          1       0.77      1.00      0.87       962

avg / total       0.59      0.77      0.67      1250

/Users/tin/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

SVM Sigmoid: 0.751200 (0.012439)
Test--  SVM Sigmoid :  0.7696

             precision    recall  f1-score   support

          0       0.00      0.00      0.00       288
          1       0.77      1.00      0.87       962

avg / total       0.59      0.77      0.67      1250

/Users/tin/anaconda3/lib/python3.7/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)